from .auth import login
from .user import UserViewSet
from .supplier import SupplierViewSet
from .product_type import ProductTypeViewSet
from .category import CategoryViewSet
from .product import ProductViewSet
from .sale import SaleViewSet
from .doctor import DoctorViewSet
from .patient import PatientViewSet
from .prescription import PrescriptionViewSet
from .stock_movement import StockMovementViewSet
from .report import ReportViewSet