import datetime
import string
import secrets
from django.db import models
from .abstracts import UpdatableAbstractModel

def generate_rx_number():
    """Generate a unique RX number like: RX-20260603-A1B2"""
    today_str = datetime.date.today().strftime('%Y%m%d')
    chars = string.ascii_uppercase + string.digits
    # FIX: Use secrets.choice() in a comprehension
    random_str = ''.join(secrets.choice(chars) for _ in range(4))
    return f"RX-{today_str}-{random_str}"

class Prescription(UpdatableAbstractModel):
    class Status(models.TextChoices):
        PENDING = 'pending', 'Pending'
        VERIFIED = 'verified', 'Verified'
        DISPENSED = 'dispensed', 'Dispensed'
        REJECTED = 'rejected', 'Rejected'

    prescription_number = models.CharField(max_length=30, unique=True, default=generate_rx_number)
    doctor = models.ForeignKey('Doctor', on_delete=models.SET_NULL, null=True, blank=True, related_name='prescriptions')
    patient = models.ForeignKey('Patient', on_delete=models.SET_NULL, null=True, blank=True, related_name='prescriptions')
    prescription_date = models.DateField()
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    verified_by = models.ForeignKey('User', on_delete=models.SET_NULL, null=True, blank=True, related_name='verified_prescriptions')
    notes = models.TextField(blank=True)

    def save(self, *args, **kwargs):
        # The prescription_number is now auto-generated by the field default.
        # We only need to auto-set the date if it wasn't provided.
        if not self.prescription_date:
            self.prescription_date = datetime.date.today()
            
        return super().save(*args, **kwargs)

    class Meta:
        db_table = 'prescriptions'
        ordering = ['-created_at']

    def __str__(self):
        return self.prescription_number


class PrescriptionItem(UpdatableAbstractModel):
    prescription = models.ForeignKey('Prescription', on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True, related_name='prescription_items')
    quantity_prescribed = models.PositiveIntegerField()
    dosage_instructions = models.CharField(max_length=200, blank=True)
    is_dispensed = models.BooleanField(default=False)

    class Meta:
        db_table = 'prescription_items'

    def __str__(self):
        product_name = self.product.name if self.product else "Unknown Product"
        return f"{self.prescription.prescription_number} - {product_name}"