# Generated by Django 6.0.5 on 2026-06-05 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_category_product_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitem',
            name='updated_at',
        ),
    ]
