# Generated by Django 6.0.5 on 2026-06-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_remove_sale_updated_at_remove_saleitem_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='suppliers',
            new_name='supplier',
        ),
    ]
