# Generated by Django 6.0.5 on 2026-06-03 12:16

import medicines.core.models.prescription
import medicines.core.models.sale
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_rename_suppliers_stockmovement_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_number',
            field=models.CharField(default=medicines.core.models.prescription.generate_rx_number, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(default=medicines.core.models.sale.generate_sale_number, max_length=30, unique=True),
        ),
    ]
