# Generated by Django 6.0.5 on 2026-06-06 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_remove_saleitem_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='suppliers',
        ),
    ]
