# Generated by Django 6.0.5 on 2026-06-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='first', max_length=150, verbose_name='First Name'),
        ),
    ]
