# Generated by Django 6.0.5 on 2026-06-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='updated_at',
        ),
    ]
