# Generated by Django 6.0.4 on 2026-05-08 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='requires_expiration',
            field=models.BooleanField(default=True, help_text='Products of this type have expiration dates (e.g., Medicine)'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='requires_prescription',
            field=models.BooleanField(default=False, help_text='Product of this type requires a prescription to purchase'),
        ),
    ]
