# Generated by Django 6.0.4 on 2026-05-08 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('ml', 'Milliliter (mL)'), ('g', 'Gram (g)'), ('mg', 'Milligram (mg)'), ('vial', 'Vial'), ('ampoule', 'Ampoule'), ('tube', 'Tube'), ('bottle', 'Bottle'), ('piece', 'Piece'), ('pack', 'Pack'), ('roll', 'Roll'), ('box', 'Box'), ('set', 'Set'), ('diaper', 'Diaper'), ('wipes', 'Wipes'), ('sachet', 'Sachet'), ('unit', 'Unit')], default='tablet', max_length=20),
        ),
    ]
