# Generated by Django 6.0.4 on 2026-05-08 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_product_base_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='reference',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='references',
            field=models.CharField(blank=True, help_text='Manual reference for adjustments or other movements...', max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='For OUT movements from Sales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='medicines.sale'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='suppliers',
            field=models.ForeignKey(blank=True, help_text='For IN movements from Suppliers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='medicines.supplier'),
        ),
    ]
