# Generated by Django 6.0.4 on 2026-05-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_category_updated_at_doctor_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='sale_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='medicines.saleitem'),
        ),
    ]
