# Generated by Django 6.0.4 on 2026-05-08 02:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_producttype_requires_expiration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='product_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='medicines.producttype', verbose_name='product type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'product_type'), name='unique_category_per_product_type'),
        ),
    ]
