# Generated by Django 6.0.5 on 2026-05-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_stockmovement_sale_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier')], default='admin', max_length=20),
        ),
    ]
