# Generated by Django 6.0.4 on 2026-05-01 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_supplier_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.category'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='medicines', to='medicines.supplier'),
        ),
    ]
