# Generated by Django 6.0.4 on 2026-05-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0003_remove_stockmovement_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockmovement',
            old_name='references',
            new_name='reference',
        ),
    ]
