# Generated by Django 6.0.4 on 2026-05-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_rename_references_stockmovement_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('return_customer', 'Return from Customer'), ('adjustment_in', 'Adjustment (In)'), ('sale', 'Sale'), ('expired', 'Expired'), ('damaged', 'Damaged'), ('return_supplier', 'Return to Supplier'), ('adjustment_out', 'Adjustment (Out)')], max_length=20, verbose_name='reason'),
        ),
    ]
