# Generated by Django 6.0.4 on 2026-05-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0004_medicine_category_medicine_supplier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='supplier',
            new_name='suppliers',
        ),
    ]
