# Generated by Django 6.0.4 on 2026-05-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0006_alter_prescription_options_prescription_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescriptionitem',
            old_name='dosage_instruction',
            new_name='dosage_instructions',
        ),
    ]
