# Generated by Django 6.0.4 on 2026-05-06 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0008_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='medicine',
            name='base_unit',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('ml', 'Milliliter (mL)'), ('g', 'Gram (g)'), ('mg', 'Milligram (mg)'), ('piece', 'Piece'), ('tube', 'Tube'), ('bottle', 'Bottle')], default='tablet', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medicines', to='medicines.producttype'),
        ),
    ]
